#!/usr/bin/env bash
#
# Clone a GIT Repository to user home
#
# Copyright (C) 2021  Gilbertsoft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Force some bash options see https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -eo pipefail
IFS=$'\n\t'

# Activate debugging if $DEBUG is set to 1
[ -z "$DEBUG" ] & [ "${DEBUG}" == 1 ] && set -o xtrace


# Functions
load_config () {
    if [ -f ".env" ]; then
        source .env
    fi

    if [ -f ".env.local" ]; then
        source .env.local
    fi

    if [ -f ".env.${WEBSITE_CONTEXT}" ]; then
        source .env.${WEBSITE_CONTEXT}
    fi

    if [ -f ".env.${WEBSITE_CONTEXT}.local" ]; then
        source .env.${WEBSITE_CONTEXT}.local
    fi
}

check_config () {
    if [ -z "$GIS_REPOSITORY" ]; then
        echo "Variable GIS_REPOSITORY is not set, aborting the installer. Please set it to the desired repository url before running the installer."
        exit 1
    fi    

    if [ -z "$GIS_BRANCH" ]; then
        GIS_BRANCH="main"
    fi    

    if [ -z "$GIS_SETUP" ]; then
        GIS_SETUP="setup"
    fi    
}

clone_repository() {
    # Check for an existing git repository
    if [ -d ".git" ]; then
        echo "*****************************************************************************"
        echo "* A git repository does already exist, the installer will use the current   *"
        echo "* branch to continue the setup process.                                     *"
        echo "*                                                                           *"
        echo "* If you like to do a fresh installation, run the following command:        *"
        echo "*                                                                           *"
        echo "*  'rm -fr .git && ./installer'                                             *"
        echo "*                                                                           *"
        echo "*****************************************************************************"

        # Reset hard and update
        git reset -q --hard
        git pull -q
    else
        # Clone the repository
        git clone -q --depth=1 --branch=${GIS_BRANCH} ${GIS_REPOSITORY} tmp/git-installer

        # Move .git to current directory
        mv tmp/git-installer/.git .git

        # Delete tmp/git-installer
        rm -fr tmp/git-installer

        # Reset hard and update
        git reset -q --hard
        git pull -q
    fi
}

post_setup () {
    # Run setup script
    if [ -f "${GIS_SETUP}" ]; then
        . ./${GIS_SETUP}
    fi
}


# Main
load_config
check_config

# Change directory to destination
cd ~/$GIS_DESTINATION

clone_repository
post_setup
