#!/usr/bin/env bash
#
# Setup the GIT Installer Script
#
# Copyright (C) 2021  Gilbertsoft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Force some bash options see https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -eo pipefail
IFS=$'\n\t'

# Activate debugging if $DEBUG is set to 1
[ -z "$DEBUG" ] & [ "${DEBUG}" == 1 ] && set -o xtrace

# Get the directory containing this script
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


# Functions
setup_links () {
    ln -fs $__dir/gis /usr/local/bin/gis
}


# Main
setup_links
